# -*- coding: utf-8 -*-
"""t_dist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaqEf9GUfw02HgZAmabrjyi16RPokaHa
"""

import numpy as np
from scipy import stats

# Given data
sample_mean = 1.8
pop_mean = 2
sample_std = 0.15
n = 10
alpha = 0.01  # 99% confidence

# Calculate t-statistic
t_stat = (sample_mean - pop_mean) / (sample_std / np.sqrt(n))
print(f"t-statistic: {t_stat:.3f}")

# Calculate critical t-value
t_critical = stats.t.ppf(alpha, df=n-1)
print(f"Critical t-value: {t_critical:.3f}")

# Calculate p-value
p_value = stats.t.cdf(t_stat, df=n-1)
print(f"p-value: {p_value:.6f}")

# Decision
if t_stat < t_critical:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")